### ISSUE TITLE
editAudio method doesn't work on Android 11.

### ISSUE THREAD

**Issue by shaan-mephobic** [LucJosin/on_audio_edit#5]
This is what I do,
 ```
  Map<TagType, dynamic> tags = {
    TagType.TITLE: title,
    TagType.ARTIST: artist,
    TagType.GENRE: genre,
  };
  bool song = await OnAudioEdit().editAudio(data, tags);  // data = "/storage/..."
  print(song);
```
I give permission to the folder which contains the song and yet I get,

> I/on_audio_exception(18448): java.io.FileNotFoundException: No content provider:
I/flutter (18448): false

I assumed it had to do something with newer android permissions so I tried giving the app the `all_files_access` but still had no luck.

**Comment by shaan-mephobic** [comment]
I've tried [audiotagger](https://pub.dev/packages/audiotagger) package but it requires the `all_files_access` permission for android 11 and play store rejected my app since the permission is not the app's core functionality.
This is what google says about core functionality,

> Core functionality is defined as the main purpose of the app. Without this core functionality, the app is "broken" or rendered unusable. The core functionality, as well as any core features that comprise this core functionality, must all be prominently documented and promoted in the app's description.

(eg: An antivirus, file manager)

So please consider making it work without the need of `all_files_access`.

I don't know how but [Blackplayer](https://play.google.com/store/apps/details?id=com.kodarkooperativet.blackplayerex&hl=en_IN&gl=US) supports editing files without the need of any additional permissions.

**Comment by LucasPJS** [comment]
For some reason i'm getting `Cannot modify file /storage/...` even when song is located outside the sdcard, which should work. On version `1.2.0` will be possible to set `searchInsideFolders` when using `readAudio` but, still required the user 'extra' permission(Android 10 or above).

I'll keep researching to find a method to only require the 'extra' permission when the song/audio is from sdcard.
